### ISSUE TITLE
Cannot use in Node.js

### ISSUE THREAD

**Issue by TotallyInformation** [FalconSoft/dataPipe#1]
Doesn't appear to be a way to get it to work in Node.js even after installing via npm. What `require` statement should be used? I've tried a few and none seem to work.

There also appears to be an error in the JS example with missing {} inside the select function:

```
.select(g => 
    r = {
      country: dataPipe(g).first().country,
      names: dataPipe(g).map(r => r.name).join(", "),
      count: dataPipe(g).count()
    };
    return r
  )
```

Should I think be:

```
.select(g => {
    r = {
      country: dataPipe(g).first().country,
      names: dataPipe(g).map(r => r.name).join(", "),
      count: dataPipe(g).count()
    };
    return r
  })
```

**Comment by ViktorKukurba** [comment]
@TotallyInformation I've updated examples `dataPipe/src/examples/`, most of them relate to version`0.2.22`, but the next one should also work in version `0.2.20` (probably one that you've installed) https://github.com/FalconSoft/dataPipe/blob/36c67e4876ef8514cdcd6cb94a516d9b58e6978f/src/examples/cjs/datapipe.js#L1-L20

README was updated as well. The first snippet you've provided relates to usage with [JSPython](https://jspython.dev/) in [Worksheet Systems App](https://worksheet.systems/code).

**Comment by TotallyInformation** [comment]
Thanks a lot for that. It works fine. Now to test with some bigger datasets :-)

**Comment by TotallyInformation** [comment]
Sorry, while the basic example from an array works, what about reading from CSV?

The `fromCsv` function doesn't seem to be surfaced for using in Node.js at all?

**Comment by ppaska** [comment]
@TotallyInformation 
Please try the following example

```js
const { dataPipe } = require('datapipe-js');
const fetch = require('node-fetch');

async function main() {

    const dataUrl = "https://raw.githubusercontent.com/FalconSoft/sample-data/master/CSV/sample-testing-data-100.csv";
    const csv = await (await fetch(dataUrl)).text();

    return dataPipe()
        .fromCsv(csv)
        .groupBy(r => r.Country)
        .select(g => ({
            country: dataPipe(g).first().Country,
            sales: dataPipe(g).sum(i => i.Sales),
            avg: dataPipe(g).avg(i => i.Sales),
            count: g.length
        })
        )
        .where(r => r.sales > 5000)
        .sort("sales DESC")
        .toArray();
}

main()
    .then(console.log)
    .catch(console.error)
```

**Comment by TotallyInformation** [comment]
Thanks, that works - you might want to update your documentation though since part of your documented API is not valid.
