### ISSUE TITLE
Flatten is missing in exported DataPipe object type

### ISSUE THREAD

**Issue by vlatal** [FalconSoft/dataPipe#2]
Hi, firstly thanks for a great project.
I tried to use flatten on DataPipe object, but the type is missing it. Could you add it?

Also in web docs it is misspelled as "Flattern".

One last thing: in web docs, there is a mention that groupBy can also take string or array of strings. Again types denies that.

**Comment by ppaska** [comment]
yeah, feel free to fork and raise PR with your changes

**Comment by ppaska** [comment]
fixed and added flattenObject method as well
